import Head from "next/head";
import { ReactNode } from "react";
import { GetServerSideProps } from "next";

import MainLayout from "@/components/Layout/MainLayout";
import { ParsedUrlQuery } from "querystring";
import { ChapterType } from "@/types";
import { getChapterDetailHandle } from "@/services/chapter.services";
import Link from "next/link";
import { iconArrowTop, iconBook, iconOclock } from "../../../../public/icons";
import ScrollOnTop from "@/components/Layout/ScrollOnTop";
import { convertTime } from "@/utils/convertTime";

interface Params extends ParsedUrlQuery {
    slug: string;
}

export interface ChapterDetailPageProps {
    chapter?: ChapterType;
}

const ChapterDetailPage = ({ chapter }: ChapterDetailPageProps) => {
    console.log(chapter);

    if (!chapter) {
        return null;
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <ScrollOnTop />
                <div className="max-w-5xl min-h-[300px] mx-auto px-4 grid bg-[#eae4d3] rounded-xl ">
                    <div className="my-4 mx-7 grid">
                        {/* Navigate */}
                        <div className="flex justify-between mb-12">
                            <Link
                                href={`/truyen/${chapter?.novelSlug}/chuong-${
                                    chapter?.chapterNumber - 1
                                }`}
                                className={`${chapter.chapterNumber == 1 && "pointer-events-none text-gray-400 fill-gray-400" }`}
                            >
                                <span className="py-2 px-7 border rounded-full flex items-center bg-white bg-opacity-50 font-semibold select-none">
                                    <i className="-rotate-90 w-3 mr-2 block">{iconArrowTop}</i>
                                    Chương trước
                                </span>
                            </Link>
                            <Link
                                href={`/truyen/${chapter?.novelSlug}/chuong-${
                                    chapter?.chapterNumber + 1
                                }`}
                                className={``}
                            >
                                <span className="py-2 px-7 border rounded-full flex items-center bg-white bg-opacity-50 font-semibold select-none">
                                    Chương sau
                                    <i className="rotate-90 w-3 ml-2 block">{iconArrowTop}</i>
                                </span>
                            </Link>
                        </div>

                        <div className="text-3xl font-medium mb-6">
                            Chương {chapter.chapterNumber}: {chapter.title}
                        </div>
                        <div className="mb-4 flex justify-between">
                            <div className="flex items-center">
                                <i className="w-4 block">{iconBook}</i>
                                <Link href={`/truyen/${chapter.novelSlug}`} className="">
                                    <h2 className=" ml-2">{chapter.novelName}</h2>
                                </Link>
                            </div>
                            <div className="flex items-center">
                                <i className="w-4 block">{iconOclock}</i>
                                <span className="">
                                    <h2 className=" ml-2">{convertTime(chapter.updatedAt)}</h2>
                                </span>
                            </div>
                        </div>
                        <span className="w-36 mx-auto my-5 border-b border-gray-500"></span>
                        <div
                            className="text-2xl leading-relaxed grid"
                            dangerouslySetInnerHTML={{
                                __html: chapter?.content || "Lỗi hiển thị",
                            }}
                        />

                        {/* Navigate */}
                        <div className="flex justify-between mt-8 mb-5">
                            <Link
                                href={`/truyen/${chapter?.novelSlug}/chuong-${
                                    chapter?.chapterNumber - 1
                                }`}
                                className={`${chapter.chapterNumber == 1 && "pointer-events-none text-gray-400 fill-gray-400" }`}
                            >
                                <span className="py-2 px-7 border rounded-full flex items-center bg-white bg-opacity-50 font-semibold select-none">
                                    <i className="-rotate-90 w-3 mr-2 block">{iconArrowTop}</i>
                                    Chương trước
                                </span>
                            </Link>
                            <Link
                                href={`/truyen/${chapter?.novelSlug}/chuong-${
                                    chapter?.chapterNumber + 1
                                }`}
                                className={``}
                            >
                                <span className="py-2 px-7 border rounded-full flex items-center bg-white bg-opacity-50 font-semibold select-none">
                                    Chương sau
                                    <i className="rotate-90 w-3 ml-2 block">{iconArrowTop}</i>
                                </span>
                            </Link>
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
};

export const getServerSideProps: GetServerSideProps = async ({ query, res }) => {
    const novelSlug = query.novelSlug as string;
    const chapterNumber = query.chapterNumber as string;

    const chapterResponse = await getChapterDetailHandle(
        novelSlug,
        chapterNumber.split("chuong-")[1]
    );
    // increaseViewChapterHandle(slug, chapterNumber)

    if (!chapterResponse) {
        return {
            props: {
                chapter: null,
            },
        };
    }

    return {
        props: {
            chapter: chapterResponse.data?.chapter || null,
        },
    };
};

ChapterDetailPage.getLayout = (page: ReactNode) => {
    return <MainLayout isBannerPage={false}>{page}</MainLayout>;
};

export default ChapterDetailPage;
