import Head from "next/head";
import { ReactNode } from "react";
import { GetServerSideProps, GetStaticProps, NextPage } from "next";

import { REVALIDATE_TIME } from "@/constants";
import MainLayout from "@/components/Layout/MainLayout";
import { getNovelsByHighlyRatedHandle, getNovelsByOutstandingHandle, getNovelsByPageHandle, getReadingNovelHandle } from "@/services/novels.services";
import { NovelType, ReviewType } from "@/types";
import { getReviewsByNovelHandle } from "@/services/review.services";
import WrapperLayout from "@/components/Layout/WrapperLayout";
import dynamic from "next/dynamic";
import { getAccessToken, getAccessTokenOnServer } from "@/services/cookies.servies";
import useSWR from "swr";
import axios from "axios";

type NovelHighlyRated = NovelType & { mediumScore: number }
interface HighlyRatedProps {
    novels?: NovelHighlyRated[]
}

export interface PageHomeProps {
    data: any
    novelsOutstending?: NovelType[]
    novelsJustUpdated?: NovelType[]
    novelsHighlyRated?: HighlyRatedProps[]
    novelsLatestReviews?: ReviewType[]
    novelsJustCompleted?: NovelType[]
}


const Outstanding = dynamic(
    () => import("@/components/Share/Outstanding", {
        ssr: false,
    } as ImportCallOptions)
)
const JustUpdated = dynamic(
    () => import("@/components/Share/JustUpdated", {
        ssr: false,
    } as ImportCallOptions)
)

const Reading = dynamic(
    () => import("@/components/Share/Reading", {
        ssr: false,
    } as ImportCallOptions)
)
const HighlyRated = dynamic(
    () => import("@/components/Share/HighlyRated", {
        ssr: false,
    } as ImportCallOptions)
)
const LatestReviews = dynamic(
    () => import("@/components/Share/LatestReviews", {
        ssr: false,
    } as ImportCallOptions)
)
const JustPosted = dynamic(
    () => import("@/components/Share/JustPosted", {
        ssr: false,
    } as ImportCallOptions)
)
const JustCompleted = dynamic(
    () => import("@/components/Share/JustCompleted", {
        ssr: false,
    } as ImportCallOptions)
)


const HomePage = ({ data = [], novelsOutstending = [], novelsJustUpdated = [], novelsHighlyRated = [], novelsLatestReviews = [], novelsJustCompleted = [] } : PageHomeProps ) => {

    // const fetchReadingNovel = async (query: string) => {
    //     const token = getAccessToken();
    //     if(!token) {
    //         return null
    //     }
    //     const res = await axios.get(`http://localhost:4000/api/novels/reading${query}`, {
    //       headers: {
    //         Authorization: `Bearer ${token}`,
    //       },
    //     });
      
    //     if (res.data.success) {
    //       return res.data.readingNovel;
    //     }
      
    //     return null;
    // };
    
    const { data: novelReading } = useSWR<{ novels: any }>(
        `?page=1`, 
        async (query) => {
            const token = getAccessToken();
            if(!token) {
                throw new Error();
            }
            const res = await axios.get(`http://localhost:4000/api/novels/reading${query}`, {
            headers: {
                Authorization: `Bearer ${token}`,
            },
            });

            if(!res.data.success || !res) {
                console.log("lỗi: ", 2)
                throw new Error();
            }
            
            console.log("lỗi: ", res.data.novels)
            return {
                novels: res.data.novels
            }
        },
        {
            onErrorRetry: (error, _, __, revalidate, { retryCount }) => {
                if(error.status === 404) {
                    return
                }
                if(retryCount >= 1) {
                    return
                }
                setTimeout(() => {
                    revalidate({ retryCount })
                }, 2000)
            }
        }
    );
    
    console.log("novelReading: ", novelReading?.novels);
 

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>

                <WrapperLayout className="min-h-screen">
                    <div className="flex flex-col lg:flex-row">
                        <div className="lg:w-8/12">
                            <Outstanding novels={novelsOutstending}/>
                        </div>
                        <div className="lg:w-4/12 hidden lg:block">
                            <Reading readingNovel={novelReading?.novels}/>
                        </div>
                    </div>
                    <div className="hidden xl:block">
                        <JustUpdated novels={novelsJustUpdated}/>
                    </div>
                    <div className="flex flex-col lg:flex-row my-6">
                        <div className="lg:w-8/12">
                            <HighlyRated novels={novelsHighlyRated as NovelHighlyRated[]}/>
                        </div>
                        <div className="lg:w-4/12">
                            <LatestReviews reviews={novelsLatestReviews}/>
                        </div>
                    </div>
                    <div className="hidden lg:flex flex-col lg:flex-row my-6">
                        <div className="lg:w-4/12">
                            <JustPosted novels={novelsOutstending}/>
                        </div>
                        <div className="lg:w-8/12">
                            <JustCompleted novels={novelsJustCompleted}/>
                        </div>
                    </div>
                </WrapperLayout>

            </main>
        </>
    );
}

export const getStaticProps : GetStaticProps = async (context) => {

    const query = context;
    const data = { page: 1 }

    const novelsResponse = await getNovelsByPageHandle("1");
    const novelsOutstandingResponse = await getNovelsByOutstandingHandle(1);
    const novelsHighlyRatedResponse = await getNovelsByHighlyRatedHandle(1);
    const reviewsResponse = await getReviewsByNovelHandle(data as ReviewType & { page: number })
    const novelReading = await getReadingNovelHandle(1)

    return {
        props: {
            novelsOutstending: novelsOutstandingResponse?.data.novels || null,
            novelsJustUpdated: novelsResponse?.data.novels || null,
            novelsReading: context.locale || null,
            novelsHighlyRated: novelsHighlyRatedResponse?.data.novels || null,

            novelsJustCompleted: novelsResponse?.data.novels || null,

            novelsLatestReviews: reviewsResponse?.data.reviews || null,

            // data: JSON.stringify(query.params) || null
        },
        revalidate: REVALIDATE_TIME
    }
}

// export const getServerSideProps : GetServerSideProps = async (ctx) => {

//     const query = ctx;
//     const data = { page: 1 }

//     const novelsResponse = await getNovelsByPageHandle("1");
//     const novelsOutstandingResponse = await getNovelsByOutstandingHandle(1);
//     const novelsHighlyRatedResponse = await getNovelsByHighlyRatedHandle(1);
//     const reviewsResponse = await getReviewsByNovelHandle(data as ReviewType & { page: number })

//     return {
//         props: {
//             novelsOutstending: novelsOutstandingResponse?.data.novels || null,
//             novelsJustUpdated: novelsResponse?.data.novels || null,
//             novelsReading: novelsResponse?.data.novels || null,
//             novelsHighlyRated: novelsHighlyRatedResponse?.data.novels || null,

//             novelsJustCompleted: novelsResponse?.data.novels || null,

//             novelsLatestReviews: reviewsResponse?.data.reviews || null,

//             // data: JSON.stringify(query.params) || null
//         },
//         revalidate: REVALIDATE_TIME
//     }

// }

HomePage.getLayout = (page : ReactNode) => {
    return (
        <MainLayout isBannerPage={true}>{page}</MainLayout>
    )
}

export default HomePage