import Head from "next/head";
import dynamic from "next/dynamic";
import { ReactNode, useState } from "react";
import AdminLayout from "@/components/Layout/AdminLayout";

import { Editor, EditorState, convertToRaw } from "draft-js";
import "draft-js/dist/Draft.css";
import EmojiPicker from "@/components/features/EmojiPicker";
import CommentInput from "@/components/features/CommentInput";


const AdminDashboardPage = () => {
    
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="w-full">
                    
                    <CommentInput />

                </div>
            </main>
        </>
    );
};

export default AdminDashboardPage;

AdminDashboardPage.getLayout = (page: ReactNode) => {
    return <AdminLayout>{page}</AdminLayout>;
};
