import Head from "next/head";
import { ReactNode } from "react";
import AdminLayout from "@/components/Layout/AdminLayout";

const AdminPage = () => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>
                    Account
                </div>
            </main>
        </>
    );
};

export default AdminPage;

AdminPage.getLayout = (page: ReactNode) => {
    return (
        <AdminLayout>{page}</AdminLayout>
    );
};
