import Head from "next/head";
import { ReactNode, useState } from "react";
import MainLayout from "@/components/Layout/MainLayout";
import AdminLayout from "@/components/Layout/AdminLayout";

const AdminSettingsPage = () => {
    // const [isDrop, setIsDrop] = useState(false)
    const [isShowing, setIsShowing] = useState(false);

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>
                    Settings
                </div>
            </main>
        </>
    );
};

export default AdminSettingsPage;

AdminSettingsPage.getLayout = (page: ReactNode) => {
    return (
        <AdminLayout>{page}</AdminLayout>
    );
};
