import Head from "next/head";
import { ReactNode, useEffect, useState } from "react";
import MainLayout from "@/components/Layout/MainLayout";
import AccountLayout from "@/components/Layout/AccountLayout";

const AccountPage = () => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>

                    Accout

                </div>
            </main>
        </>
    );
}

export default AccountPage;

AccountPage.getLayout = (page: ReactNode) => {

    return (
        <MainLayout isBannerPage={false}>
            <AccountLayout>{page}</AccountLayout>
        </MainLayout>
    )
}


// import dynamic from "next/dynamic";
// import { Datepicker, Input, initTE } from "tw-elements";
// const _ = typeof window !== "undefined" && dynamic(import("tw-elements"));