import Head from "next/head";
import { ReactNode } from "react";
import MainLayout from "@/components/Layout/MainLayout";
import AccountLayout from "@/components/Layout/AccountLayout";


const AccountPaymentPage = () => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>
                    <div className="flex grid-cols-3 border">
                        <button className="flex-1 py-2">MoMo</button>
                        <button className="flex-1 py-2">VNPay</button>
                        <button className="flex-1 py-2">Tài khoản ngân hàng</button>
                    </div>
                </div>
            </main>
        </>
    );
}

export default AccountPaymentPage;

AccountPaymentPage.getLayout = (page: ReactNode) => {

    return (
        <MainLayout isBannerPage={false}>
            <AccountLayout tab="/account/payment">{page}</AccountLayout>
        </MainLayout>
    )
}